//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2026.03.08 at 06:30:41 PM ULAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://num.edu.mn/auth", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package mn.edu.num.auth;
